[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "write", path = "./index.html"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
