[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hot-chain-svg/=contracts/',
    'hot-chain-svg-script/=script/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'hot-chain-svg-test/=test/'
]

[profile.watch]
ffi = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
