/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface RendererInterface extends utils.Interface {
  functions: {
    "example()": FunctionFragment;
    "render(uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "example" | "render"): FunctionFragment;

  encodeFunctionData(functionFragment: "example", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "render",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "example", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "render", data: BytesLike): Result;

  events: {};
}

export interface Renderer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RendererInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    example(overrides?: CallOverrides): Promise<[string]>;

    render(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  example(overrides?: CallOverrides): Promise<string>;

  render(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    example(overrides?: CallOverrides): Promise<string>;

    render(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    example(overrides?: CallOverrides): Promise<BigNumber>;

    render(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    example(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    render(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
